---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the remote EDPM deployment (uses nodeset name: openstack-edpm)
components:
  - https://github.com/openstack-k8s-operators/architecture/dt/uni01alpha/edpm?ref=main
