---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

wait_condition_retry_delay: 5
wait_condition_retries: 50
manifests_dir: /home/zuul/manifests
automation:
  stages: []

openstack_operators_image: quay.io/openstack-k8s-operators/openstack-operator-index:latest
openstack_operator_channel: alpha

edpm_podman_registries: []
edpm_container_registry_logins: {}

hotstack_rhos_release_args: >-
  18.0 -r 9.4 -p latest-RHOSO-18.0-RHEL-9
hotstack_edpm_bootstrap_command: "common/scripts/upstream_edpm_bootstrap_command.sh.j2"
hotstack_install_ca_url: https://url.corp.redhat.com/hotstack-ca
hotstack_rhos_release_rpm: https://url.corp.redhat.com/hotstack-rhos-release-latest-noarch-rpm

# For convinience, a default patches for nodesets
# * Sets edpm_bootstrap_command
# * Set registries/registry logins if not already set in the nodeset YAML.
hotstack_default_nodeset_patches:
  - path: spec.nodeTemplate.ansible.ansibleVars.edpm_bootstrap_command
    value: >-
      {{
        lookup('ansible.builtin.template', hotstack_edpm_bootstrap_command)
      }}
  - path: spec.nodeTemplate.ansible.ansibleVars.edpm_podman_registries
    value: "{{ edpm_podman_registries }}"
    where:
      - path: spec.nodeTemplate.ansible.ansibleVars.edpm_podman_registries
        value: null
  - path: spec.nodeTemplate.ansible.ansibleVars.edpm_container_registry_logins
    value: "{{ edpm_container_registry_logins }}"
    where:
      - path: spec.nodeTemplate.ansible.ansibleVars.edpm_podman_registries
        value: null
