---
stages:
  - name: TopoLVM Dependencies
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/topolvm-deps-stages.yaml.j2")
      }}

  - name: Dependencies
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/deps-stages.yaml.j2")
      }}

  - name: Cinder LVM
    stages: >-
      {{
        lookup("ansible.builtin.file",
               "common/stages/cinder-lvm-label-stages.yaml")
      }}

  - name: TopoLVM
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/topolvm-stages.yaml.j2")
      }}

  - name: OLM Openstack
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/olm-openstack-stages.yaml.j2")
      }}

  - name: Control Plane (NNCP and OpenStackControlPlane)
    kustomize:
      directory: scenarios/uni01alpha/kustomize/control-plane
    wait_conditions:
      - >-
        oc wait -n openstack nncp -l osp/nncm-config-type=standard
        --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
        --timeout=180s
      - >-
        oc wait -n openstack openstackcontrolplane controlplane
        --for condition=Ready --timeout=30m

  - name: Dataplane SSH key secret
    shell: >-
      oc create -n openstack secret generic dataplane-ansible-ssh-private-key-secret
      --save-config --dry-run=client
      --from-file=ssh-privatekey=/home/zuul/.ssh/id_rsa
      --from-file=ssh-publickey=/home/zuul/.ssh/id_rsa.pub
      --type=Opaque -o yaml | oc apply -f -
    wait_conditions:
      - >-
        oc wait -n openstack secret dataplane-ansible-ssh-private-key-secret
        --for jsonpath='{.metadata.name}'=dataplane-ansible-ssh-private-key-secret
        --timeout=30s

  - name: Nova migration SSH key secret
    shell: >-
      oc create -n openstack secret generic nova-migration-ssh-key
      --save-config --dry-run=client
      --from-file=ssh-privatekey=/home/zuul/.ssh/id_nova_migrate
      --from-file=ssh-publickey=/home/zuul/.ssh/id_nova_migrate.pub
      --type=Opaque -o yaml | oc apply -f -
    wait_conditions:
      - >-
        oc wait -n openstack secret nova-migration-ssh-key
        --for jsonpath='{.metadata.name}'=nova-migration-ssh-key
        --timeout=30s

  - name: Networker nodeset
    kustomize:
      directory: scenarios/uni01alpha/kustomize/networker

  - name: EDPM nodeset
    kustomize:
      directory: scenarios/uni01alpha/kustomize/edpm

  - name: Wait for nodesets (Networker and EDPM)
    wait_conditions:
      - >-
        oc wait -n openstack openstackdataplanenodeset networker-nodes
        --for condition=SetupReady --timeout=10m
      - >-
        oc -n openstack wait openstackdataplanenodeset openstack-edpm
        --for condition=SetupReady --timeout=10m

  - name: Networker deployment
    kustomize:
      directory: scenarios/uni01alpha/kustomize/networker-deployment

  - name: EDPM deployment
    kustomize:
      directory: scenarios/uni01alpha/kustomize/dataplane-deployment

  - name: Wait for deployments (Networker and EDPM)
    wait_conditions:
      - oc wait -n openstack jobs.batch bootstrap-networker-deploy-networker-nodes --for condition=Complete --timeout=10m
      - oc wait -n openstack jobs.batch bootstrap-edpm-deployment-openstack-edpm --for condition=Complete --timeout=10m
      - oc wait -n openstack jobs.batch configure-network-networker-deploy-networker-nodes --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch configure-network-edpm-deployment-openstack-edpm --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch validate-network-networker-deploy-networker-nodes --for condition=Complete --timeout=1m
      - oc wait -n openstack jobs.batch validate-network-edpm-deployment-openstack-edpm --for condition=Complete --timeout=1m
      - oc wait -n openstack jobs.batch install-os-networker-deploy-networker-nodes --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch install-os-edpm-deployment-openstack-edpm --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch configure-os-networker-deploy-networker-nodes --for condition=Complete --timeout=3m
      - oc wait -n openstack jobs.batch configure-os-edpm-deployment-openstack-edpm --for condition=Complete --timeout=3m
      - oc wait -n openstack jobs.batch ssh-known-hosts-edpm-deployment --for condition=Complete --timeout=1m
      - oc wait -n openstack jobs.batch run-os-networker-deploy-networker-nodes --for condition=Complete --timeout=3m
      - oc wait -n openstack jobs.batch run-os-edpm-deployment-openstack-edpm --for condition=Complete --timeout=3m
      - oc wait -n openstack jobs.batch reboot-os-networker-deploy-networker-nodes --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch reboot-os-edpm-deployment-openstack-edpm --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch install-certs-networker-deploy-networker-nodes --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch install-certs-edpm-deployment-openstack-edpm --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch ovn-networker-deploy-networker-nodes --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch ovn-edpm-deployment-openstack-edpm --for condition=Complete --timeout=5m
      - oc wait -n openstack jobs.batch neutron-metadata-networker-deploy-networker-nodes --for condition=Complete --timeout=10m
      - oc wait -n openstack openstackdataplanedeployment networker-deploy --for condition=Ready --timeout=10m
      - oc wait -n openstack jobs.batch neutron-metadata-edpm-deployment-openstack-edpm --for condition=Complete --timeout=10m
      - oc wait -n openstack jobs.batch libvirt-edpm-deployment-openstack-edpm --for condition=Complete --timeout=20m
      - oc wait -n openstack jobs.batch nova-edpm-deployment-openstack-edpm --for condition=Complete --timeout=20m
      - oc wait -n openstack jobs.batch telemetry-edpm-deployment-openstack-edpm --for condition=Complete --timeout=10m
      - oc -n openstack wait openstackdataplanedeployment edpm-deployment --for condition=Ready --timeout=10m
      - timeout --foreground 15m hotstack-nova-discover-hosts --namespace openstack --num-computes 2

  - name: "Minor update :: openstack-operators OLM"
    stages: >-
      {{
        lookup('ansible.builtin.template',
               'common/stages/openstack-olm-update.yaml.j2')
      }}
    run_conditions:
      - >-
        {{
          openstack_operators_update is defined and
          openstack_operators_update | bool
        }}

  - name: "Minor update :: controlplane and dataplane"
    stages: >-
      {{
        lookup('ansible.builtin.template',
               'common/stages/openstack-update.yaml.j2')
      }}
    run_conditions:
      - >-
        {{
          openstack_update is defined and
          openstack_update | bool
        }}
