---
stages:
  - name: Cinder LVM
    stages: >-
      {{
        lookup("ansible.builtin.file",
               "common/stages/cinder-lvm-label-stages.yaml")
      }}

  - name: TopoLVM
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/topolvm-stages.yaml.j2")
      }}

  - name: OLM Dependencies
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/olm-deps-stages.yaml.j2")
      }}

  - name: OLM Openstack
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/olm-openstack-stages.yaml.j2")
      }}

  - name: NodeNetworkConfigurationPolicy (nncp)
    manifest: manifests/control-plane/nncp/nncp.yaml
    wait_conditions:
      - >-
        oc wait -n openstack nncp -l osp/nncm-config-type=standard
        --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
        --timeout=5m

  - name: OpenstackControlPlane
    manifest: manifests/control-plane/control-plane.yaml
    wait_conditions:
      - >-
        oc wait -n openstack openstackcontrolplane controlplane
        --for condition=Ready --timeout=60m

  - name: Dataplane SSH key secret
    cmd: >-
      oc create -n openstack secret generic dataplane-ansible-ssh-private-key-secret
      --save-config --dry-run=client
      --from-file=ssh-privatekey=/home/zuul/.ssh/id_rsa
      --from-file=ssh-publickey=/home/zuul/.ssh/id_rsa.pub
      --type=Opaque -o yaml | oc apply -f -
    wait_conditions:
      - >-
        oc wait -n openstack secret dataplane-ansible-ssh-private-key-secret
        --for jsonpath='{.metadata.name}= dataplane-ansible-ssh-private-key-secret'
        --timeout=30s

  - name: Nova migration SSH key secret
    cmd: >-
      oc create -n openstack secret generic nova-migration-ssh-key
      --save-config --dry-run=client
      --from-file=ssh-privatekey=/home/zuul/.ssh/id_nova_migrate
      --from-file=ssh-publickey=/home/zuul/.ssh/id_nova_migrate.pub
      --type=Opaque -o yaml | oc apply -f -
    wait_conditions:
      - >-
        oc wait -n openstack secret nova-migration-ssh-key
        --for jsonpath='{.metadata.name}=nova-migration-ssh-key'
        --timeout=30s

  - name: Networker nodeset
    manifest: manifests/networker/nodeset/nodeset.yaml
    patches: "{{ hotstack_default_nodeset_patches }}"

  - name: EDPM nodeset
    manifest: manifests/edpm/edpm.yaml
    patches: "{{ hotstack_default_nodeset_patches }}"

  - name: Wait for nodesets (Networker and EDPM)
    wait_conditions:
      - >-
        oc wait -n openstack openstackdataplanenodeset networker-nodes
        --for condition=SetupReady --timeout=10m
      - >-
        oc -n openstack wait openstackdataplanenodeset openstack-edpm
        --for condition=SetupReady --timeout=10m

  - name: Networker deployment
    manifest: manifests/networker/networker.yaml

  - name: EDPM deployment
    manifest: manifests/dataplane.yaml

  - name: Wait for deployments (Networker and EDPM)
    wait_conditions:
      - >-
        oc wait -n openstack openstackdataplanedeployment networker-deploy
        --for condition=Ready --timeout=40m
      - >-
        oc -n openstack wait openstackdataplanedeployment edpm-deployment
        --for condition=Ready --timeout=40m

  - name: Wait for expected compute services (OSPRH-10942)
    script: |
      set -xe -o pipefail
      COMPUTES=3
      RETRIES=10
      COUNTER=0
      oc project openstack
      until [ $(oc rsh openstackclient openstack compute service list --service nova-compute -f value | wc -l) -eq "$COMPUTES" ]; do
        if [[ "$COUNTER" -ge "$RETRIES" ]]; then
          exit 1
        fi
        COUNTER=$[$COUNTER +1]
        sleep 10
      done

  - name: Run nova-manage discover_hosts and wait for host records (OSPRH-10942)
    script: |
      set -xe -o pipefail
      COMPUTES={{ 2 | int + 4 }}
      RETRIES=10
      COUNTER=0
      oc project openstack
      until [ $(oc rsh nova-cell1-conductor-0 nova-manage cell_v2 list_hosts | wc -l) -eq "$COMPUTES" ]; do
        if [[ "$COUNTER" -ge "$RETRIES" ]]; then
          exit 1
        fi
        oc rsh nova-cell1-conductor-0 nova-manage cell_v2 discover_hosts --verbose
        COUNTER=$[$COUNTER +1]
        sleep 10
      done
