---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the remote networker deployment (uses nodeset name: networker-nodes)
components:
  - https://github.com/openstack-k8s-operators/architecture/dt/uni01alpha/networker?ref=main
