!
hostname leaf01
!
router bgp 65001
 bgp router-id 10.255.255.3
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.255.255.1 remote-as 65001
 neighbor 10.255.255.1 description spine01
 neighbor 10.255.255.1 update-source Loopback0
 neighbor 10.255.255.2 remote-as 65001
 neighbor 10.255.255.2 description spine02
 neighbor 10.255.255.2 update-source Loopback0
 !
 address-family l2vpn evpn
  neighbor 10.255.255.1 activate
  neighbor 10.255.255.2 activate
  advertise-all-vni
 exit-address-family
!
end
