!
hostname spine01
!
router bgp 65001
 bgp router-id 10.255.255.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.255.255.3 remote-as 65001
 neighbor 10.255.255.3 description leaf01
 neighbor 10.255.255.3 update-source Loopback0
 neighbor 10.255.255.4 remote-as 65001
 neighbor 10.255.255.4 description leaf02
 neighbor 10.255.255.4 update-source Loopback0
 !
 address-family l2vpn evpn
  neighbor 10.255.255.3 activate
  neighbor 10.255.255.3 route-reflector-client
  neighbor 10.255.255.4 activate
  neighbor 10.255.255.4 route-reflector-client
 exit-address-family
!
end
