---
- name: Bootstrap architecutre on Openstack cloud
  hosts: localhost
  gather_facts: true
  strategy: linear
  pre_tasks:
    - name: Load stack output vars from file
      ansible.builtin.include_vars:
        file: "{{ stack_name }}-outputs.yaml"
        name: stack_outputs

    - name: Add controller-0 to the Ansible inventory
      ansible.builtin.add_host: "{{ hotstack_work_dir | default(playbook_dir) }}/{{ stack_outputs.controller_ansible_host }}"

    - name: Load dataplane SSH keys vars
      ansible.builtin.include_vars:
        file: "{{ hotstack_work_dir | default(playbook_dir) }}/dataplane_ssh_keys_vars.yaml"

    - name: Load automation vars
      ansible.builtin.include_vars:
        file: "{{ test_operator_automation_vars_file }}"
        name: automation

  roles:
    - role: hotloop
      delegate_to: controller-0
      vars:
        work_dir: "{{ scenario_dir }}/{{ scenario }}/test-operator"
        automation: "{{ automation }}"
