---
all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    controller_ssh_pub_key: >-
      {{ lookup('ansible.builtin.file',
         lookup('ansible.builtin.first_found',
                ['~/.ssh/id_rsa.pub',
                 '~/.ssh/id_ed25519.pub']))
      }}
