---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Wait for MicroShift API to be reachable
  ansible.builtin.command:
    cmd: >-
      {{ bin_dir }}/oc version
      --kubeconfig={{ microshift_kube_config_dir }}/config
  register: _api_check
  until: _api_check.rc == 0
  retries: 30
  delay: 10
  changed_when: false

- name: Wait for MicroShift node to be Ready
  ansible.builtin.command:
    cmd: >-
      {{ bin_dir }}/oc wait nodes --all
      --kubeconfig={{ microshift_kube_config_dir }}/config
      --for=condition=Ready
      --timeout=600s
  register: _node_ready
  until: _node_ready.rc == 0
  retries: 30
  delay: 10
  changed_when: false

- name: Wait for all pods to be Ready
  ansible.builtin.command:
    cmd: >-
      {{ bin_dir }}/oc wait pods --all --all-namespaces
      --kubeconfig={{ microshift_kube_config_dir }}/config
      --for=condition=Ready
      --field-selector=status.phase!=Succeeded
      --timeout=600s
  changed_when: false
