system {
    host-name switch;
    root-authentication {
        plain-text-password-value "jnpr123";
    }
    login {
        user jnpr {
            class super-user;
            authentication {
                plain-text-password-value "jnpr123";
            }
        }
    }
    services {
        ssh {
            root-login allow;
        }
        netconf {
            ssh;
        }
    }
    management-instance;
}
chassis {
    fpc 0 {
        pic 0 {
            number-of-ports 56;
        }
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                dhcp;
            }
        }
    }
    ge-0/0/0 {
        description "trunk to devstack";
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
                vlan members [ default ];
            }
        }
    }
    ge-0/0/1 {
        description "ironic0 access port";
    }
    ge-0/0/2 {
        description "ironic1 access port";
    }
}
routing-instances {
    mgmt_junos {
        routing-options {
            static {
                route 0.0.0.0/0 next-hop 192.168.32.1;
            }
        }
    }
}
