#!/usr/bin/env python3
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""
Interface Wait Script for cEOS

Waits for the management interface (eth0) to be available before allowing
cEOS initialization to proceed. This runs inside the cEOS container.
"""

import os
import sys
import time

for i in range(30):
    if os.path.exists("/sys/class/net/eth0"):
        print("Management interface ready")
        sys.exit(0)
    time.sleep(1)

print("Timeout waiting for management interface")
sys.exit(1)
