---
stages:
  - name: Dependencies
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/deps-stages.yaml.j2")
      }}

  - name: Cinder LVM
    stages: >-
      {{
        lookup("ansible.builtin.file",
               "common/stages/cinder-lvm-label-stages.yaml")
      }}

  - name: TopoLVM
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/topolvm-stages.yaml.j2")
      }}

  - name: OLM Openstack
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/olm-openstack-stages.yaml.j2")
      }}

  - name: NodeNetworkConfigurationPolicy (nncp)
    manifest: manifests/networking/nncp.yaml
    wait_conditions:
      - >-
        oc wait -n openstack nncp -l osp/nncm-config-type=standard
        --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
        --timeout=180s

  - name: NetworkAttchmentDefinition (NAD)
    manifest: manifests/networking/nad.yaml

  - name: MetalLB - L2Advertisement and IPAddressPool
    manifest: manifests/networking/metallb.yaml

  - name: Netconfig
    manifest: manifests/networking/netconfig.yaml

  - name: NGS config (Networking Generic Switch)
    manifest: manifests/ngs/config.yaml
    wait_conditions:
      - >-
        oc wait -n openstack secret neutron-switch-config
        --for jsonpath='{.metadata.name}'=neutron-switch-config
        --timeout=30s

  - name: Openstack Version
    manifest: manifests/openstack-version.yaml
    patches:
      - path: spec.customContainerImages
        value: "{{ customContainerImages }}"
    wait_conditions:
      - >-
        oc wait -n openstack openstackversions.core.openstack.org controlplane
        --for condition=Initialized --timeout=30m
    run_conditions:
      - >-
        {{ customContainerImages is defined and customContainerImages | length > 0 }}

  - name: OpenstackControlPlane
    manifest: manifests/control-plane.yaml
    wait_conditions:
      - >-
        oc -n openstack wait openstackcontrolplanes.core.openstack.org controlplane
        --for condition=OpenStackControlPlaneDNSReadyCondition --timeout=600s

  - name: Extra DNS LoadBalancer on Ironic network
    manifest: manifests/dnsmasq-dns-ironic.yaml
    wait_conditions:
      - >-
        oc wait -n openstack service dnsmasq-dns-ironic
        --for jsonpath='.status.loadBalancer' --timeout=60s

  - name: Wait for OpenstackControlPlane
    wait_conditions:
      - >-
        oc wait -n openstack openstackcontrolplane controlplane
        --for condition=Ready --timeout=30m

  - name: Update openstack-operators OLM
    stages: >-
      {{
        lookup('ansible.builtin.template',
               'common/stages/openstack-olm-update.yaml.j2')
      }}
    run_conditions:
      - >-
        {{
          openstack_operators_update is defined and
          openstack_operators_update | bool
        }}

  - name: Wait for condition MinorUpdateAvailable True
    wait_conditions:
      - >-
        oc -n openstack wait openstackversions.core.openstack.org controlplane
        --for=condition=MinorUpdateAvailable=True --timeout=10m
    run_conditions:
      - "{{ openstack_update is defined and openstack_update | bool }}"

  - name: "Minor update :: Create OpenStackVersion patch"
    documentation: |
      This creates a patch file `{{ manifests_dir }}/patches/openstack_version_patch.yaml`
      If `openstack_update_custom_images` is defined it will populate the customContainerImages
      in the OpenstackVersion YAML patch.
    shell: >-
      {{
        lookup('ansible.builtin.template',
              'common/scripts/create_openstack_version_patch.sh.j2')
      }}
    run_conditions:
      - "{{ openstack_update is defined and openstack_update | bool }}"

  - name: "Minor update :: Update the target version in the OpenStackVersion custom resource (CR)"
    documentation: |
      The `hotstack-openstack-version-patch` script will get the `availableVersion`
      and us it to replace the string `__TARGET_VERSION__` in the patch file and
      apply the patch using `oc patch` command.
    command: >-
      hotstack-openstack-version-patch --namespace openstack --name controlplane
      --file {{ manifests_dir }}/patches/openstack_version_patch.yaml
    wait_conditions:
      - oc -n openstack wait openstackversions.core.openstack.org controlplane
        --for=condition=Ready --timeout=10m
    run_conditions:
      - "{{ openstack_update is defined and openstack_update | bool }}"
