---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  namespace: openstack
data:
  # Cinder configuration
  cinderVolumes.lvm-iscsi.replicas: "1"
  cinderVolumes.lvm-iscsi.nodeSelector.openstack.org/cinder-lvm: ""
  cinderVolumes.lvm-iscsi.customServiceConfig: |
    [lvm]
    image_volume_cache_enabled = false
    volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
    volume_group = cinder-volumes
    target_protocol = iscsi
    target_helper = lioadm
    volume_backend_name = lvm_iscsi
    target_ip_address=172.18.0.10
    target_secondary_ip_addresses = 172.19.0.10
  cinderBackup.replicas: "1"
  cinderBackup.customServiceConfig: |
    [DEFAULT]
    backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver

  # Glance configuration
  glance.default.replicas: "3"
  glance.customServiceConfig: |
    [DEFAULT]
    debug = True
    enabled_backends = default_backend:swift

    [glance_store]
    default_backend = default_backend

    [default_backend]
    swift_store_create_container_on_put = True
    swift_store_auth_version = 3
    swift_store_auth_address = {{ .KeystoneInternalURL }}
    swift_store_endpoint_type = internalURL
    swift_store_user = service:glance
    swift_store_key = {{ .ServicePassword }}

  # Swift configuration
  swift.enabled: "true"

  # Ironic configuration
  ironic.enabled: "true"
  ironic.rpcTransport: "oslo"
  ironic.ironicConductors.0.customServiceConfig: |
    [conductor]
    power_state_change_timeout = 120

    [pxe]
    kernel_append_params = console=ttyS0

    [neutron]
    cleaning_network = provisioning
    provisioning_network = provisioning
    rescuing_network = provisioning
    inspection_network = provisioning
  ironic.ironicInspector.customServiceConfig: |
    [capabilities]
    boot_mode = true

    [processing]
    update_pxe_enabled = false

  # Octavia configuration
  octavia.enabled: "true"
  octavia.amphoraImageContainerImage: "quay.io/gthiemonge/octavia-amphora-image"
  octavia.apacheContainerImage: "registry.redhat.io/ubi9/httpd-24:latest"
  octavia.availabilityZones: |-
    - zone-1
  octavia.octaviaAPI.networkAttachments: |-
    - internalapi
  octavia.octaviaHousekeeping.networkAttachments: |-
    - octavia
  octavia.octaviaHealthManager.networkAttachments: |-
    - octavia
  octavia.octaviaWorker.networkAttachments: |-
    - octavia
  octavia.redisServiceName: "redis"

  # Redis configuration
  redis.enabled: "true"
  redis.templates: |-
    redis:
      replicas: 1

  # Heat configuration
  heat.enabled: "true"
  heat.customServiceConfig: |
    [clients_heat]
    endpoint_type = public
    insecure: true

  # Telemetry configuration
  telemetry.enabled: "true"
  telemetry.metricStorage.enabled: "true"
  telemetry.autoscaling.enabled: "true"
  telemetry.ceilometer.enabled: "true"

  # OVN configuration
  ovn.ovnController.availability-zones: |-
    - zone-1
  ovn.ovnController.nicMappings: |-
    datacentre: ocpbr
    ironic: ironic
    octavia: octbr

  # Neutron configuration
  neutron.customServiceConfig: |
    [DEFAULT]
    vlan_transparent = true
    agent_down_time = 600
    router_distributed = true
    router_scheduler_driver = neutron.scheduler.l3_agent_scheduler.ChanceScheduler
    allow_automatic_l3agent_failover = true
    debug = true
    default_availability_zones = zone-1,zone-2

    [agent]
    report_interval = 300

    [database]
    max_retries = -1
    db_max_retries = -1

    [keystone_authtoken]
    region_name = regionOne
    memcache_use_advanced_pool = True

    [oslo_messaging_notifications]
    driver = noop

    [oslo_middleware]
    enable_proxy_headers_parsing = true

    [oslo_policy]
    policy_file = /etc/neutron/policy.yaml

    [ovs]
    igmp_snooping_enable = true

    [ovn]
    ovsdb_probe_interval = 60000
    ovn_emit_need_to_frag = true

    [ml2]
    type_drivers = geneve,vxlan,vlan,flat,local
    tenant_network_types = geneve,flat
  neutron.ml2MechanismDrivers: |-
    - ovn
    - baremetal

  # Nova configuration
  nova.cellTemplates: |-
    cell0:
      cellDatabaseAccount: nova-cell0
      cellDatabaseInstance: openstack
      cellMessageBusInstance: rabbitmq
      hasAPIAccess: true
    cell1:
      cellDatabaseAccount: nova-cell1
      cellDatabaseInstance: openstack-cell1
      cellMessageBusInstance: rabbitmq-cell1
      hasAPIAccess: true
      novaComputeTemplates:
        compute-ironic:
          computeDriver: ironic.IronicDriver
