#!/bin/bash
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu -o pipefail

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi

CEOS_VERSION=$(echo "${DIB_CEOS_IMAGE:-}" \
    | xargs basename 2>/dev/null \
    | sed -n 's/.*cEOS64-lab-\(.*\)\.tar\.xz/\1/p')

if [ -z "${CEOS_VERSION}" ]; then
    CEOS_VERSION="latest"
fi

echo "INFO: Importing cEOS image on build host (version: ${CEOS_VERSION})"
podman import "${DIB_CEOS_IMAGE}" localhost/ceos:${CEOS_VERSION}

echo "INFO: Saving cEOS image as podman archive"
mkdir -p "${TMP_HOOKS_PATH}"
podman save -o "${TMP_HOOKS_PATH}/ceos-image.tar" localhost/ceos:${CEOS_VERSION}

echo "INFO: Compressing cEOS podman archive"
gzip "${TMP_HOOKS_PATH}/ceos-image.tar"

echo "INFO: Cleaning up imported image from build host"
podman rmi localhost/ceos:${CEOS_VERSION}

echo "INFO: cEOS image processed and ready for installation (version: ${CEOS_VERSION})"
