---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - https://github.com/openstack-k8s-operators/gitops/components/argocd/annotations?ref=main
  - https://github.com/openstack-k8s-operators/gitops/components/rhoso/dataplane?ref=main

patches:
  - path: dataplane-nodeset-patch.yaml
  - path: dataplane-deployment-patch.yaml
