#!/bin/bash
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# NXOS v64.10.x requires GNS3's custom OVMF firmware to boot.
# The standard OVMF from the distro does not work with NXOS.

set -eu -o pipefail

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi

OVMF_URL="${DIB_NXOS_OVMF_URL:-https://sourceforge.net/projects/gns-3/files/Qemu%20Appliances/OVMF-edk2-stable202305.fd.zip/download}"
OVMF_ZIP="${TMP_HOOKS_PATH}/OVMF-edk2-stable202305.fd.zip"
OVMF_FD="${TMP_HOOKS_PATH}/OVMF-edk2-stable202305.fd"

mkdir -p "${TMP_HOOKS_PATH}"

if [ ! -f "${OVMF_FD}" ]; then
    curl -fSL -o "${OVMF_ZIP}" "${OVMF_URL}"
    unzip -o -d "${TMP_HOOKS_PATH}" "${OVMF_ZIP}"
    rm -f "${OVMF_ZIP}"

    if [ ! -f "${OVMF_FD}" ]; then
        echo "ERROR: Expected firmware file not found after extraction: ${OVMF_FD}"
        ls -la "${TMP_HOOKS_PATH}"
        exit 1
    fi
fi

echo "INFO: GNS3 OVMF firmware ready: ${OVMF_FD}"
