---
apiVersion: v1
kind: ConfigMap
metadata:
  name: topolvm-lvmd-0
  namespace: topolvm-system
data:
  lvmd.yaml: |
    socket-name: /run/topolvm/lvmd.sock
    device-classes:
      - name: default
        volume-group: microshift
        spare-gb: 0
        default: true
