---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ironic
  namespace: sushy-emulator
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ironic",
      "type": "bridge",
      "bridge": "ironic",
      "mtu": 1442,
      "ipam": {
        "type": "whereabouts",
        "range": "172.20.1.0/24",
        "range_start": "172.20.1.71",
        "range_end": "172.20.1.75"
      }
    }
