---
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - name: local-storage
      fstype: xfs
      default: true
      deviceSelector:
        paths:
        - /dev/vdb
        forceWipeDevicesAndDestroyAllData: true
      thinPoolConfig:
        name: topolvms_thin_pool
        sizePercent: 90
        overprovisionRatio: 10
