#!/bin/bash
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu -o pipefail

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi

echo "INFO: Enabling SONiC systemd services..."

systemctl enable sonic-import.service
systemctl enable sonic.service

echo "INFO: SONiC services enabled successfully"
