---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: dataplane-update-ovn
  namespace: openstack
spec:
  nodeSets:
    - openstack-edpm
    - networker-nodes
  servicesOverride:
    - ovn
