---
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
  namespace: openshift-machine-api
spec:
  provisioningNetwork: "Disabled"
  watchAllNamespaces: true
