#!/bin/bash
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu -o pipefail

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi

SONIC_IMAGE_PATH="/tmp/in_target.d/sonic-image.tar.gz"

if [ ! -f "${SONIC_IMAGE_PATH}" ]; then
    echo "ERROR: SONiC image file not found in build directory: ${SONIC_IMAGE_PATH}"
    echo "ERROR: This should have been processed by extra-data.d/11-copy-sonic-image"
    exit 1
fi

SONIC_VERSION=$(echo "${DIB_SONIC_IMAGE:-}" \
    | xargs basename 2>/dev/null \
    | sed -n 's/docker-sonic-vs-\?\(.*\)\.gz/\1/p')

if [ -z "${SONIC_VERSION}" ]; then
    SONIC_VERSION="latest"
fi

mkdir -p /var/lib/sonic
cp "${SONIC_IMAGE_PATH}" /var/lib/sonic/sonic-image.tar.gz
echo "${SONIC_VERSION}" > /var/lib/sonic/sonic-version.txt

echo "INFO: SONiC podman archive installed (version: ${SONIC_VERSION})"
