---
stages:
  - name: Set a multiattach volume type and create it if needed
    documentation: >-
      Creates and configures a multiattach volume type in OpenStack that allows
      volumes to be attached to multiple instances simultaneously. This is essential
      for shared storage scenarios and high-availability configurations.
    shell: |
      set -xe -o pipefail
      oc project openstack

      oc rsh openstackclient openstack volume type show multiattach &>/dev/null || \
          oc rsh openstackclient openstack volume type create multiattach

      oc rsh openstackclient openstack volume type set --property multiattach="<is> True" multiattach

  - name: Create public network if needed
    documentation: >-
      Creates an external public network that provides connectivity to the outside world.
      This network uses a flat provider network type mapped to the 'datacentre' physical
      network and serves as the gateway for floating IP assignments.
    shell: |
      set -xe -o pipefail
      oc project openstack

      oc rsh openstackclient openstack network show public &>/dev/null || \
        oc rsh openstackclient openstack network create public \
          --external \
          --no-share \
          --default \
          --provider-network-type flat \
          --provider-physical-network datacentre

  - name: Create subnet on public network if needed
    documentation: >-
      Creates a subnet on the public network with a specific IP range (192.168.122.0/24)
      and allocation pool. This subnet provides DHCP services and defines the gateway
      for external connectivity. The allocation pool reserves IPs 171-250 for floating IPs.
    shell: |
      set -xe -o pipefail
      oc project openstack

      oc rsh openstackclient openstack subnet show public_subnet &>/dev/null || \
        oc rsh openstackclient openstack subnet create public_subnet \
          --network public \
          --subnet-range 192.168.122.0/24 \
          --allocation-pool start=192.168.122.171,end=192.168.122.250 \
          --gateway 192.168.122.1 \
          --dhcp

  - name: Create private network if needed
    documentation: >-
      Creates a shared private network for internal communication between OpenStack instances.
      This network is shared across tenants and provides isolated internal connectivity
      separate from the external public network.
    shell: |
      set -xe -o pipefail
      oc project openstack

      oc rsh openstackclient openstack network show private &>/dev/null || \
        oc rsh openstackclient openstack network create private --share

  - name: Create subnet on private network if needed
    documentation: >-
      Creates a subnet on the private network with IP range 10.2.0.0/24 for internal
      instance communication. This subnet includes DHCP services and allocates IPs
      from 10.2.0.10 to 10.2.0.250 for instance assignments.
    shell: |
      set -xe -o pipefail
      oc project openstack

      oc rsh openstackclient openstack subnet show private_subnet &>/dev/null || \
        oc rsh openstackclient openstack subnet create private_subnet \
          --network private \
          --subnet-range 10.2.0.0/24 \
          --allocation-pool start=10.2.0.10,end=10.2.0.250 \
          --gateway 10.2.0.1 \
          --dhcp

  - name: Run tempest
    documentation: >-
      Executes comprehensive OpenStack validation tests using the Tempest framework.
    manifest: tempest-tests.yml
    wait_conditions:
      - >-
        oc wait -n openstack tempests.test.openstack.org tempest-tests
        --for condition=ServiceConfigReady --timeout=120s
    wait_pod_completion:
      - namespace: openstack
        labels:
          operator: test-operator
          service: tempest
          workflowStep: "0"
        timeout: 3600
        poll_interval: 15
      - namespace: openstack
        labels:
          operator: test-operator
          service: tempest
          workflowStep: "1"
        timeout: 3600
        poll_interval: 15
