---
- job:
    name: hotstack-pre-commit
    nodeset: hotstack-pod
    description: |
      Run pre-commit in pod
    timeout: 450
    run: ci/playbooks/pre-commit.yml

- job:
    name: devsetup-hotstack-os
    parent: base-minimal
    nodeset: hotstack-image-vexxhost
    description: |
      Test HotsTac(k)os containerized OpenStack devsetup
    timeout: 2700
    required-projects:
      - opendev.org/zuul/zuul-jobs
    roles:
      - zuul: opendev.org/zuul/zuul-jobs
    pre-run: ci/playbooks/pre-hotstack-os.yml
    run: ci/playbooks/run-hotstack-os.yml
    post-run: ci/playbooks/post-hotstack-os.yml
    files:
      - ^devsetup/hotstack-os/.*
      - ^ci/playbooks/pre-hotstack-os\.yml
      - ^ci/playbooks/run-hotstack-os\.yml
      - ^ci/playbooks/post-hotstack-os\.yml

- job:
    name: base-hotstack-vexxhost
    parent: base-hotstack
    nodeset: hotstack-image-vexxhost
    description: |
      Base job for Hotstack scenarios on Vexxhost
    vars:
      cloud_name: vexxhost
      scenario_dir: >-
        {{
          [
            ansible_user_dir,
            zuul.projects['github.com/openstack-k8s-operators/hotstack'].src_dir,
            'scenarios'
          ] | ansible.builtin.path_join
        }}
      hotstack_overrides:
        stack_parameters:
          cdrom_disk_bus: sata
          compute_params:
            image: cs9stream-genericcloud
          networker_params:
            image: cs9stream-genericcloud
          bmh_params:
            image: cs9stream-genericcloud
          ironic_params:
            image: cs9stream-genericcloud
            # vpu: 2 ram 4GB disk: 40GB
            flavor: ci.m1.medium
      hotstack_enable_nova_console_poller: true
      hotstack_enable_nova_console_recorder: true
      sushy_emulator_os_vmedia_rescue_bus: sata
    pre-run:
      - ci/playbooks/pre-deploy.yml
    run:
      - ci/playbooks/run-deploy.yml
      - ci/playbooks/run-tests.yml

- job:
    name: vexxhost-hotstack-ipxe-image
    parent: base-hotstack-ixpe-image-periodic
    nodeset: hotstack-image-vexxhost
    description: |
      Build Hotstack ipxe image
    timeout: 900
    vars:
      cloud_name: vexxhost
    files:
      - ^ipxe/.*

- job:
    name: vexxhost-hotstack-blank-image
    parent: base-hotstack-blank-image-periodic
    nodeset: hotstack-image-vexxhost
    description: |
      Build Hotstack blank image
    timeout: 900
    vars:
      cloud_name: vexxhost
    files:
      - ^images/.*

- job:
    name: vexxhost-hotstack-controller-image
    parent: base-hotstack-controller-image-periodic
    nodeset: hotstack-image-vexxhost
    description: |
      Build Hotstack controller image
    timeout: 900
    vars:
      cloud_name: vexxhost
    files:
      - ^images/.*

- job:
    name: vexxhost-hotstack-sno-2-bm
    parent: base-hotstack-vexxhost
    nodeset: hotstack-image-vexxhost
    description: |
      Hotstack scenario: sno-2-bm
    timeout: 5400
    attempts: 1
    vars:
      scenario: sno-2-bm
    files:
      - ^scenarios/sno-2-bm/.*
      - ^roles/redfish_virtual_bmc/.*
      - ^roles/redfish_vbmc_podman/.*
      - ^roles/nova_console_recorder/.*
      - ^roles/nova_console_poller/.*

- job:
    name: vexxhost-hotstack-3-nodes
    parent: base-hotstack-vexxhost
    nodeset: hotstack-image-vexxhost
    description: |
      Hotstack scenario: 3-nodes
    timeout: 10800
    attempts: 1
    vars:
      scenario: 3-nodes
    files:
      - ^scenarios/3-nodes/.*
      - ^roles/controller/.*
      - ^roles/dataplane_ssh_keys/.*
      - ^roles/heat_stack/.*
      - ^roles/hotlogs/.*
      - ^roles/hotloop/.*
      - ^roles/ocp_agent_installer/.*

- job:
    name: vexxhost-hotstack-3-nodes-update
    parent: base-hotstack-vexxhost
    nodeset: hotstack-image-vexxhost
    description: |
      Hotstack scenario: 3-nodes
    timeout: 10800
    attempts: 1
    vars:
      scenario: 3-nodes
      openstack_operators_update: true
      openstack_update: true
      openstack_operators_image: quay.io/openstack-k8s-operators/openstack-operator-index-upgrade:latest
      openstack_operator_channel: alpha
      openstack_operator_starting_csv: v0.4.0
    files:
      - ^scenarios/3-nodes/.*

- job:
    name: vexxhost-hotstack-multi-nodeset
    parent: base-hotstack-vexxhost
    nodeset: hotstack-image-vexxhost
    description: |
      Hotstack scenario: multi-nodeset
    timeout: 10800
    attempts: 1
    vars:
      scenario: multi-nodeset
    files:
      - ^scenarios/multi-nodeset/.*

- job:
    name: vexxhost-hotstack-uni01alpha
    parent: base-hotstack-vexxhost
    nodeset: hotstack-image-vexxhost
    description: |
      Hotstack scenario: uni01alpha
    timeout: 18000
    attempts: 1
    vars:
      scenario: uni01alpha
    files:
      - ^scenarios/uni01alpha/.*
