---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git://controller-0.openstack.lab/openstack-deployment
    targetRevision: main
    path: manifests/operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
