---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-switch-config
  namespace: openstack
stringData:
  03-ml2-genericswitch.conf: |
    [ngs]
    session_log_file = /var/log/neutron/ngs.log

    [ml2]
    tenant_network_types = geneve,vlan,flat

    [ml2_type_vlan]
    network_vlan_ranges = datacentre,ironic:100:120

    [genericswitch:nxos]
    device_type = netmiko_arista_eos
    ngs_mac_address = 22:dd:fe:aa:1b:08
    # 101 = ironic
    # 102 = tenant-vlan102 (native vlan)
    # 103 = tenant-vlan103
    # 104 = tenant-vlan104
    ngs_allowed_vlans = 101,102,103,104
    ngs_port_default_vlan = 102
    ngs_trunk_ports = ethernet1/1
    ngs_physical_networks = ironic
    ip = veos.openstack.lab
    username = admin
    password = password
type: Opaque
